services:
  app:
    extends:
      file: docker-compose.dev.yml
      service: app

  postgres:
    extends:
      file: docker-compose.dev.yml
      service: postgres

  redis:
    extends:
      file: docker-compose.dev.yml
      service: redis

volumes:
  postgres_data:
