from app.routers import (
    accounting,
    audit_log,
    auth,
    b2b,
    customers,
    dashboard,
    expenses_refactored,
    farm,
    home,
    hr,
    import_data,
    inventory,
    pos,
    production,
    products,
    receive,
    refunds,
    reports,
    suppliers,
    users,
)

ROUTERS = (
    auth.router,
    home.router,
    pos.router,
    import_data.router,
    dashboard.router,
    products.router,
    customers.router,
    receive.router,
    suppliers.router,
    inventory.router,
    hr.router,
    accounting.router,
    production.router,
    b2b.router,
    farm.router,
    reports.router,
    users.router,
    refunds.router,
    expenses_refactored.router,
    audit_log.router,
)

__all__ = ["ROUTERS"]
